apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
      app: demo
